//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Repositorios.SqlServer.Ado.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.Repositorios.SqlServer.Ado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].ClienteSelecionarPorPais
        ///       @country varchar(15)
        ///       
        ///AS
        ///       SELECT CustomerId, ContactName, Phone, City
        ///       from Customers
        ///       where Country = @country.
        /// </summary>
        internal static string CREATEPROCEDUREClienteSelecionarPorPais {
            get {
                return ResourceManager.GetString("CREATEPROCEDUREClienteSelecionarPorPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE PaisSelecionar   
        ///AS
        ///       Select distinct Country From Customers
        ///       where Country is not null
        ///       order by Country.
        /// </summary>
        internal static string CREATEPROCEDUREPaisSelecionar {
            get {
                return ResourceManager.GetString("CREATEPROCEDUREPaisSelecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].TransportadoraAtualizar
        ///       @id int,
        ///       @companyName nvarchar(40),
        ///       @phone nvarchar(24)  
        ///AS
        ///       Update Shippers
        ///       set CompanyName = @companyName,
        ///              Phone = @phone
        ///       where ShipperId = @id.
        /// </summary>
        internal static string CREATEPROCEDURETransportadoraAtualizar {
            get {
                return ResourceManager.GetString("CREATEPROCEDURETransportadoraAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PROCEDURE [dbo].[TransportadoraExcluir]
        ///       @ShipperID int
        ///AS
        ///       Delete Shippers where ShipperID = @ShipperID.
        /// </summary>
        internal static string CreatePROCEDURETransportadoraExcluir {
            get {
                return ResourceManager.GetString("CreatePROCEDURETransportadoraExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PROCEDURE [dbo].[TransportadoraInserir]
        ///       @companyName nvarchar(40),
        ///       @phone nvarchar(24)  
        ///AS
        ///       Insert Shippers(CompanyName, Phone)
        ///       output INSERTED.ShipperID
        ///       values(@companyName, @phone).
        /// </summary>
        internal static string CreatePROCEDURETransportadoraInserir {
            get {
                return ResourceManager.GetString("CreatePROCEDURETransportadoraInserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PROCEDURE [dbo].[TransportadoraSelecionar] @shipperId int = null
        ///AS
        ///       SELECT ShipperId, CompanyName, Phone
        ///       from Shippers
        ///       where ShipperID = IsNull(@shipperId , ShipperId)
        ///       order by CompanyName.
        /// </summary>
        internal static string CreatePROCEDURETransportadoraSelecionar {
            get {
                return ResourceManager.GetString("CreatePROCEDURETransportadoraSelecionar", resourceCulture);
            }
        }
    }
}
