// <auto-generated />
namespace NorthWind.Repositorios.SqlServer.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MergeCascadeDeleteProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeCascadeDeleteProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101803376_MergeCascadeDeleteProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
