// <auto-generated />
namespace NorthWind.Repositorios.SqlServer.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClienteNovosCampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClienteNovosCampos));
        
        string IMigrationMetadata.Id
        {
            get { return "201703021657172_ClienteNovosCampos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
